replicaCount: 1

image:
  repository: hossamgbm/personal-website-app
  tag: "16"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 4173

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "200m"

ingress:
  enabled: true
  className: kong
  host: hossam.io
  tls:
    enabled: true
    secretName: mysite-ingress-tls
  annotations:
    konghq.com/strip-path: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"

configMap:
  APP: mysite
  MYSQL_HOST: registration-app-mysql.apis-services.svc.cluster.local

secretName: mysite-db-secret

secrets:
  MYSQL_USER: root
  MYSQL_PASSWORD: rootpassword
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: mysite_db
