apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-app-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    application: personal-website-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: personal-website-app
  template:
    metadata:
      labels:
        app: personal-website-app
    spec:
      containers:
        - name: personal-website-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: site-configmap
            - secretRef:
                name: {{ .Values.secretName }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
