apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.secrets.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.secrets.MYSQL_DATABASE }}
