apiVersion: v1
kind: Service
metadata:
  name: personal-website-app-svc
  namespace: {{ .Release.Namespace }}
  labels:
    application: personal-website-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: personal-website-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
